services:
  - type: web
    name: clinic-backend
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: DB_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: PPNdHrzYKhBggWeVle0GjLPJYAuWPtuL
